### ISSUE TITLE
SSHKit version error

### ISSUE THREAD

**Issue by Kulgar** [capistrano/rvm#37]
Hi!

I'm getting this error when trying to deploy: 

`Unable to activate capistrano-rvm-0.1.0, because sshkit-1.3.0 conflicts with sshkit (~> 1.2.0)`

Here are the versions of my gems (from Gemfile.lock):
- capistrano-rvm (0.1.0)
- capistrano (3.0.1)
- capistrano-bundler (1.1.1)
- capistrano-rails (1.1.0)

Strange things is that none of those Gems require sshkit 1.3.0. I also veryfied the dependencies of my other Gems, they don't require sshkit. 

Here is the full trace:

``` ruby
cap aborted!
Unable to activate capistrano-rvm-0.1.0, because sshkit-1.3.0 conflicts with sshkit (~> 1.2.0)
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2000:in `raise_if_conflicts'
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1238:in `activate'
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems.rb:194:in `rescue in try_activate'
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems.rb:191:in `try_activate'
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
/home/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/home/projects/rails_project/Capfile:18:in `<top (required)>'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
/home/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.1/lib/capistrano/application.rb:22:in `load_rakefile'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/home/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/home/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.1/lib/capistrano/application.rb:12:in `run'
/home/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.1/bin/cap:3:in `<top (required)>'
/home/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `load'
/home/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `<main>'
/home/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/home/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

Would you know what's going on? 

Thanks. :)

**Comment by Kulgar** [comment]
Ok! Apparently I managed to find and solve the problem. 

It seems that during bundle update, bundler updated sshkit to 1.3.0 because of one of the Capistrano Gems. When I tried to force the gems to use the 1.2.0 version, there were still trying to load sshkit 1.3.0. I had to remove it from my Gems: 

`$ gem uninstall sshkit -v 1.3.0`

Now it is working properly.
