### ISSUE TITLE
rake exit status: 1

### ISSUE THREAD

**Issue by wxianfeng** [capistrano/rvm#58]
hello, i use `capistrano-rvm` gem, but i meet `rake exit status: 1` error at `rake assets:precompile` this step
my stack as follows, no  more infos, how to fix it? thx

``` ruby
NFO[236b3613] Running ~/.rvm/bin/rvm 2.1.1 do bundle install --binstubs /home/admin/kanbox/www/update.labs.etao.com/shared/bin --path /home/admin/kanbox/www/update.labs.etao.com/shared/bundle --without development test --no-deployment --quiet on 10.98.60.82
INFO[236b3613] Finished in 2.680 seconds with exit status 0 (successful).
INFO[d56fe150] Running ~/.rvm/bin/rvm 2.1.1 do bundle exec rake assets:precompile on 10.98.60.82
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 10.98.60.82: rake exit status: 1
rake stdout: Nothing written
rake stderr: Nothing written
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/command.rb:97:in `exit_status='
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:148:in `block (5 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `call'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `do_request'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:561:in `channel_request'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:170:in `block (3 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `call'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:172:in `block (2 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:186:in `with_ssh'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:131:in `block in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `tap'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `_execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:59:in `block (6 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in `with'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:58:in `block (5 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:77:in `within'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:57:in `block (4 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SSHKit::Command::Failed: rake exit status: 1
rake stdout: Nothing written
rake stderr: Nothing written
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/command.rb:97:in `exit_status='
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:148:in `block (5 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `call'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `do_request'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:561:in `channel_request'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:170:in `block (3 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `call'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:172:in `block (2 levels) in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:186:in `with_ssh'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:131:in `block in _execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `tap'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `_execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:59:in `block (6 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in `with'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:58:in `block (5 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:77:in `within'
/home/admin/.rvm/gems/ruby-2.1.1/gems/capistrano-rails-1.1.1/lib/capistrano/tasks/assets.rake:57:in `block (4 levels) in <top (required)>'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/admin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: #<SSHKit::Runner::ExecuteError: Exception while executing on host 10.98.60.82: rake exit status: 1
rake stdout: Nothing written
rake stderr: Nothing written
>
```

**Comment by RajRoR** [comment]
@wxianfeng Did you found some solution to it? I'm facing it on `bundle install` task

**Comment by wxianfeng** [comment]
@RajRoR 
i removed rvm install ruby,  reinstall ruby by source to system.

the problem has gone away!
