### ISSUE TITLE
using jruby-9.0.5.0 reports `Could not find the main class: org/jruby/Main. Program will exit.`

### ISSUE THREAD

**Issue by larryzhao** [capistrano/rvm#74]
I am using `jruby-9.0.5.0` for my project. After setting up the server, I run `cap production deploy:check`, and I get:

```
DEBUG [3852050a] Running ~/.rvm/bin/rvm jruby-9.0.5.0@tagore do ruby --version as deployer@milan.jianshu.io
DEBUG [3852050a] Command: ~/.rvm/bin/rvm jruby-9.0.5.0@tagore do ruby --version
DEBUG [3852050a]    Exception in thread "main"
DEBUG [3852050a]    java.lang.UnsupportedClassVersionError: org/jruby/Main : Unsupported major.minor version 51.0
DEBUG [3852050a]
DEBUG [3852050a]        at java.lang.ClassLoader.findBootstrapClass(Native Method)
DEBUG [3852050a]
DEBUG [3852050a]        at java.lang.ClassLoader.findBootstrapClass0(ClassLoader.java:909)
DEBUG [3852050a]
DEBUG [3852050a]        at java.lang.ClassLoader.loadClass(ClassLoader.java:318)
DEBUG [3852050a]
DEBUG [3852050a]        at java.lang.ClassLoader.loadClass(ClassLoader.java:316)
DEBUG [3852050a]
DEBUG [3852050a]        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
DEBUG [3852050a]
DEBUG [3852050a]        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
DEBUG [3852050a]
DEBUG [3852050a]    Could not find the main class: org/jruby/Main. Program will exit.
```

But when I log on to the system and run command `~/.rvm/bin/rvm jruby-9.0.5.0@tagore do ruby --version`. It's all correct.

How could I fix this?

Thank you very much.

My server is running Ubuntu Server 12.04 with rvm latest installation. I am using `capistrano 3.4` and `capistrano-rvm 0.1.2`

**Comment by larryzhao** [comment]
I've found the problem. Thanks

**Comment by neotifa** [comment]
thanks for not giving us the solution
